### ISSUE TITLE
Add navbar component

### ISSUE THREAD

**Issue by Kcchouette** [KingPixil/wing#24]
Hello,

Is there a way to add a simple navbar (like that but more simpler, of course: http://bootsnipp.com/snippets/featured/navbar-search-add-on-bs-3 ) in wing?

Or is there a way to have a invisible navbar menu which can collaspe for mobile using wing 0.1.7?

Thanks

**Comment by talonbragg** [comment]
Plugins will make the site slower, don't use it. Wait, why am I giving you tips?

**Comment by KingPixil** [comment]
What do you mean @talonbragg?

Plugins will simply be included in a `plugins` folder which will be compiled into a bundled file with all of your plugins.

**Comment by Yinchie** [comment]
@KingPixil they are trolling.

**Comment by KingPixil** [comment]
@Yinchie Seems like it... 😒

**Comment by talonbragg** [comment]
Yes @Yinchie  and @KingPixil  Like he did to us on many of our projects, this is the main reason we are doing it to him because I wanted to see how he feels. I know him in real life too. He goes to my school. He has been ratting on us ever since we started coding. So I have no idea why anybody follows him or stars his repos. It is certainly unreasonable. Why even bother when he is just a waste of your time. @talonbragg.

**Comment by Yinchie** [comment]
I follow him because I make use of his Wing and liking it.

**Comment by KingPixil** [comment]
Thanks for the support @Yinchie 

@talonbragg Honestly, I would never want you to stop programming, I've never said that, all I've done before is that I made an issue on one of your repositories, listing some things you could improve, but since you obviously don't like this, I won't do it anymore.

**Comment by talonbragg** [comment]
Kabir stop wasting your childhood on our repos and telling us we are bad at programming.

**Comment by talonbragg** [comment]
@KingPixil You just want us to stop programming

**Comment by KingPixil** [comment]
Fixed in #44
